### ISSUE TITLE
New error in sc.load

### ISSUE THREAD

**Issue by giusedm** [Blu-Tiger/streamingcommunity-unofficialapi#11]
error:
`Traceback (most recent call last):
  File "/Users/peppe/Desktop/test/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peppe/Desktop/test/app.py", line 4, in <module>
    ap = sc.load('9997-il-gladiatore-ii')
  File "/Users/peppe/Desktop/test/lib/python3.13/site-packages/scuapi/scuapi.py", line 256, in load
    data = resp.json()
  File "/Users/peppe/Desktop/test/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`


code:
`from scuapi import API

sc = API('streamingcommunity.prof')
ap = sc.load('9997-il-gladiatore-ii')
print(ap)`

**Comment by Blu-Tiger** [comment]
Should be fixed now
